dockerfile specification removed from docker build

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,7 +50,7 @@ jobs:
           [ -z "$SOFTETHER_VERSION" ] && { echo "Softether version not defined"; exit 1; }
           echo -e "\n\nDockerfile:\n$( cat Dockerfile )\n\n"
 
-          docker build --rm -t croc/softether -f Dockerfile . || { echo "Docker image build fail"; exit 1; }
+          docker build --rm -t croc/softether . || { echo "Docker image build fail"; exit 1; }
           docker tag croc/softether croc/softether:$SOFTETHER_VERSION
       - name: push container
         env:
@@ -106,7 +106,7 @@ jobs:
           [ -z "$SOFTETHER_VERSION" ] && { echo "Softether version not defined"; exit 1; }
           echo -e "\n\nDockerfile:\n$( cat Dockerfile )\n\n"
 
-          docker build --rm --platform linux/arm64 -t croc/softether-arm64 -f Dockerfile . || { echo "Docker image build fail - ARM64"; exit 1; }
+          docker build --rm --platform linux/arm64 -t croc/softether-arm64 . || { echo "Docker image build fail - ARM64"; exit 1; }
           docker tag croc/softether-arm64 croc/softether-arm64:$SOFTETHER_VERSION
       - name: push container
         env:
