arm build changed to kaniko

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -84,18 +84,10 @@ jobs:
             echo -e "\nURL for $FOLDER_STRING: " 
             echo "$BASE_URL/$LATEST" | tee latest_url-$FOLDER_STRING.txt
           done
-      # buildx with quemu
-      - name: qemu setup for buildx for arm build
-        uses: docker/setup-qemu-action@v2
-      - name: setup buildx for arm build
-        id: buildx
-        uses: docker/setup-buildx-action@v2
       - name: build image - ARM 64bit
         env:
           ARCH: ARM
         run: |
-          echo "Buildx supported platforms: ${{ steps.buildx.outputs.platforms }}"
-
           LATEST_URL=$( cat latest_url-*$ARCH*.txt )
           echo "Latest URL: $LATEST_URL"
           [ -z "$LATEST_URL" ] && { echo "Latest url not found"; exit 1; }
@@ -106,9 +98,12 @@ jobs:
           [ -z "$SOFTETHER_VERSION" ] && { echo "Softether version not defined"; exit 1; }
           echo -e "\n\nDockerfile:\n$( cat Dockerfile )\n\n"
 
-          docker buildx build --rm --platform linux/arm64 -t croc/softether-arm64 . || { echo "Docker image build fail - ARM64"; exit 1; }
-          docker images | grep -i softether
-          docker tag croc/softether-arm64 croc/softether-arm64:$SOFTETHER_VERSION
+          docker --rm --privileged multiarch/qemu-user-static --reset -p yes || { echo "Multiarch setup error"; exit 1; }
+
+          ls $PWD
+          docker run -ti --rm -v $PWD:/workspace gcr.io/kaniko-project/executor --context /workspace --customPlatform linux/arm64/v8 --no-push
+          docker images
+
       - name: push container
         env:
           DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
